config/routes.rb
Composer::Application.routes.draw do
mount WillFilter::Engine => "/will_filter"
  resources :expenses


  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/expense.rb
class Expense < ActiveRecord::Base
  attr_accessible :amount, :description, :name, :vat, :user_id, :created_at
  belongs_to :user


end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  has_many :expenses
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :role_ids, :as => :admin
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me


  def to_s
    name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, :alert => exception.message
  end

end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  # GET /expenses
  # GET /expenses.json

  def index
    @expenses = Expense.filter(params: params)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @expenses }
    end
  end

  # GET /expenses/1
  # GET /expenses/1.json
  def show
    @expense = Expense.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @expense }
    end
  end

  # GET /expenses/new
  # GET /expenses/new.json
  def new
    @expense = Expense.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @expense }
    end
  end

  # GET /expenses/1/edit
  def edit
    @expense = Expense.find(params[:id])
  end

  # POST /expenses
  # POST /expenses.json
  def create

    @expense = Expense.new(params[:expense])
    @expense.user_id = current_user.id
    respond_to do |format|
      if @expense.save
        format.html { redirect_to @expense, notice: 'Expense was successfully created.' }
        format.json { render json: @expense, status: :created, location: @expense }
      else
        format.html { render action: "new" }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /expenses/1
  # PUT /expenses/1.json
  def update
    @expense = Expense.find(params[:id])

    respond_to do |format|
      if @expense.update_attributes(params[:expense])
        format.html { redirect_to @expense, notice: 'Expense was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenses/1
  # DELETE /expenses/1.json
  def destroy
    @expense = Expense.find(params[:id])
    @expense.destroy

    respond_to do |format|
      format.html { redirect_to expenses_url }
      format.json { head :no_content }
    end
  end

  private

  def sort_column
    Expense.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end

  def sort_direction
    #the first half of the following line is to prevent sql injection in the order method, s
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
  
  def update
    authorize! :update, @user, :message => 'Not authorized as an administrator.'
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user], :as => :admin)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end
    
  def destroy
    authorize! :destroy, @user, :message => 'Not authorized as an administrator.'
    user = User.find(params[:id])
    unless user == current_user
      user.destroy
      redirect_to users_path, :notice => "User deleted."
    else
      redirect_to users_path, :notice => "Can't delete yourself."
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/expenses_helper.rb
module ExpensesHelper
		def expenses_chart1_data
			  Expense.where("amount > 100")
		end




	def expenses_chart2_data
	(4.weeks.ago.to_date..Date.today).map do |date|
		{
			created_at: date,
			amount: Expense.where("date(created_at) =?", date).sum(:amount) 
		}
		end
	end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/expenses/_form.html.erb
<%= simple_form_for(@expense) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :amount %>
    <%= f.input :vat %>
    <%= f.hidden_field :user_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/expenses/edit.html.erb
<h1>Editing expense</h1>

<%= render 'form' %>

<%= link_to 'Show', @expense %> |
<%= link_to 'Back', expenses_path %>

app/views/expenses/index.html.erb
<div class="row">
  <div class="large-6 columns">
    <h3 class="subheader"> All Search Records </h3>
    <%= content_tag :div, "", id: "expenses_chart", data: { expenses: @expenses } %> 
  </div>
  <div class="large-6 columns">
    <h3 class="subheader"> All records greater than £100</h3>
    <%= content_tag :div, "", id: "expenses_chart1", data: { expenses: expenses_chart1_data } %>
  </div>

</div>

<h3 id="expense_filter" class="subheader">Create a filter</h2>

<%= will_filter_tag(@expenses)  %>



<div class="row" id="data">
  <div class="large-2 columns">
    <h3 class="subheader">Table View</h2>
  </div>
  <div class="large-3 columns left">
  <%= link_to 'New Expense', new_expense_path, class: "button", id: "new_expense_button" %>
  </div>
</div>



<table>
  <tr>
    <th width="200">Name</th>
    <th width="200">Description</th>
    <th width="200">Amount</th>
    <th width="200">VAT</th>
    <th width="200">User</th>
    <th width="200">Created at</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @expenses.each do |expense| %>
  <tr>
    <td><%= expense.name %></td>
    <td><%= expense.description %></td>
    <td><%= number_to_currency(expense.amount, unit: "&pound;") %></td>
    <td><%= expense.vat %></td>
    <td><%= expense.user %></td>
    <td><%= l expense.created_at, format: :short %></td>
    <td><%= link_to 'Show', expense %></td>
    <td><%= link_to 'Edit', edit_expense_path(expense) %></td>
    <td><%= link_to 'Destroy', expense, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

app/views/expenses/new.html.erb
<h1>New expense</h1>

<%= render 'form' %>

<%= link_to 'Back', expenses_path %>

app/views/expenses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @expense.name %>
</p>

<p>
  <b>Description:</b>
  <%= @expense.description %>
</p>

<p>
  <b>Amount:</b>
  <%= @expense.amount %>
</p>

<p>
  <b>Vat:</b>
  <%= @expense.vat %>
</p>

<p>
  <b>User:</b>
  <%= @expense.user %>
</p>


<%= link_to 'Edit', edit_expense_path(@expense) %> |
<%= link_to 'Back', expenses_path %>

app/views/home/index.html.erb
<h3>Home</h3>
<% @users.each do |user| %>
  <p>User: <%=link_to user.name, user %></p>
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <%= content_tag :div, msg, :id => "flash_#{name}" %>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
  <div class="row">
    
    <div class="large-5 columns">
      <h1><%= link_to "Expenses", root_path, :id => 'brand' %></h1>
    </div>
    <div class="large-7 columns">
      <ul class="button-group">

      <% if user_signed_in? %>
        <% if current_page?(expenses_path) %>
          <li><a href="#charts" class="button">Charts</a></li>
          <li><a href="#expense_filter" class="button">Filter</a></li>
          <li><a href="#data" class="button">Data</a></li>

        <% end %>
        <li>
        <%= link_to 'Expenses', expenses_path, class: "button" unless current_page?( expenses_path) %>
        </li>
        <li>
        <%= link_to 'Logout', destroy_user_session_path, :method=>'delete', class: "button" %>
        </li>
      <% else %>
        <li>
        <%= link_to 'Login', new_user_session_path, class: "button" %>
        </li>
      <% end %>
      <% if user_signed_in? %>
        <li>
        <%= link_to 'Edit account', edit_user_registration_path, class: "button" %>
        </li>
        <% if current_user.has_role? :admin %>
          <li>
          <%= link_to 'Admin', users_path, class: "button" %>
          </li>
        <% end %>
      <% else %>
        <li>
        <%= link_to 'Sign up', new_user_registration_path, class: "button" %>
        </li>
      <% end %>
      </ul>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Expense Viewer" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Expense Viewer" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
  <div class="row">
    <div class="large-12 columns">

    <div id="container">
      <header>
        <%= render 'layouts/navigation' %>
        <%= render 'layouts/messages' %>
      </header>
      <div id="main" role="main">
        <%= yield %>
      </div>
      <footer>
      </footer>
    </div> <!--! end of #container -->
    </div>
  </div>
  </body>
</html>

app/views/users/_user.html.erb
<div id="role-options-<%= user.id %>" class="modal" style="display: none;">
  <%= simple_form_for user, :url => user_path(user), :html => {:method => :put, :class => 'form-horizontal' } do |f| %>
    <div class="modal-header">
      <a class="close" data-dismiss="modal">&#215;</a>
      <h3>Change Role</h3>
    </div>
    <div class="modal-body">
      <%= f.input :role_ids, :collection => Role.all, :as => :radio_buttons, :label_method => lambda {|t| t.name.titleize}, :label => false, :item_wrapper_class => 'inline', checked: user.role_ids.first %>
    </div>
    <div class="modal-footer">
      <%= f.submit "Change Role", :class => "btn" %>
      <a class="btn" data-dismiss="modal" href="#">Close</a>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<h3>Users</h3>
<div class="span8">
<table class="table table-condensed">
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th>Registered</th>
      <th>Role</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= link_to user.name, user %></td>
      <td><%= user.email %></td>
      <td><%= user.created_at.to_date %></td>
      <td><%= user.roles.first.name.titleize unless user.roles.first.nil? %></td>
      <td>
        <a data-toggle="modal" href="#role-options-<%= user.id %>" class="btn btn-mini" type="button">Change role</a>
        <%= render user %>
      </td>
      <td><%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-mini') unless user == current_user %></td>
    </tr>
  <% end %>
  </tbody>
</table>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>User: <%= @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>